//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTaskList
    {
        public int Id { get; set; }
        public string Task_Name { get; set; }
        public string User_Name { get; set; }
        public string Customer_Name { get; set; }
        public System.DateTime Start_Work_Time { get; set; }
        public Nullable<System.DateTime> Finish_Work_Time { get; set; }
        public string Status { get; set; }
    }
}
